### ISSUE TITLE
instruction semantics

### ISSUE THREAD

**Issue by aquynh** [joelpx/reverse#2]
you can take advantage of some advanced API of Capstone to check the semantics of instructions.
since instructions are classified in groups, you can do in Python:

- check if an instruction is a RETURN instruction with:
    if i.group(CS_GRP_RET):
        ....

- check if an instruction is a kind of JUMP instruction with:
    if i.group(CS_GRP_JUMP):
        ....

there are few more type of groups such as CS_GRP_CALL, CS_GRP_IRET, etc. 
see `__init__.py` & `x86_const.py` for more info.

**Comment by joelpx** [comment]
I didn't know this, thank you. I will add it.

**Comment by aquynh** [comment]
if you find anything wrong on the group information (such as an instruction belongs to a wrong group, or group is totally missing), please report.

thanks.
