### ISSUE TITLE
ARM support is unlikely

### ISSUE THREAD

**Issue by pfalcon** [joelpx/reverse#31]
Just build and1.bin and behold stuff like:

~~~~
    0x8500: pop fp, pc
    if == {
        <$d>
        0x8504: r8 = r0 & (r4 << 11) # andeq r8, r0, r4, lsl #11
        0x8508: r8 = r0 & (r8 << 11) # andeq r8, r0, r8, lsl #11
        0x850c: r8 = r0 & (ip << 11) # andeq r8, r0, ip, lsl #11
    }
~~~~

i.e. it can't even detect return from function.

Out of curiosity, what made you write your own such tool, did you try to reuse an existing one?

**Comment by joelpx** [comment]
Ah yes, actually "pop pc" is not considered as a return statement. I will fix it.
This project was just a hobby and a personnal challenge ;)

**Comment by joelpx** [comment]
Fixed on master, can you confirm please ?
Thanks.

**Comment by pfalcon** [comment]
Looks better now, thanks.
