### ISSUE TITLE
No module named elftools

### ISSUE THREAD

**Issue by xorb0ss** [joelpx/reverse#38]
requirements.sh runs fine, installs everything that's needed, however:

```
python3.4 ./reverse.py tests/nestedloop1.bin

Traceback (most recent call last):
  File "./reverse.py", line 29, in <module>
    reverse(ctx)
  File "/home/reverse/lib/__init__.py", line 234, in reverse
    if not load_file(ctx):
  File "/home/reverse/lib/__init__.py", line 127, in load_file
    ctx.raw_base, ctx.raw_big_endian)
  File "/home/reverse/lib/disassembler.py", line 35, in __init__
    self.binary = Binary(filename, raw_type, raw_base, raw_big_endian)
  File "/home/reverse/lib/fileformat/binary.py", line 48, in __init__
    import lib.fileformat.elf as LIB_ELF
  File "/home/reverse/lib/fileformat/elf.py", line 20, in <module>
    from elftools.elf.elffile import ELFFile
ImportError: No module named 'elftools'
```

**Comment by joelpx** [comment]
Can you check if the package elftools is correctly installed and have correct rights (readable for all) ? The path on my distrib is /usr/lib/python3.4/site-packages/elftools/

**Comment by xorb0ss** [comment]
Embarrassing, but yes, for some reason elftools was read only. However, I seem to have stumbled upon:

```
xor~home:/ python3.4 reverse.py tests/nestedloop1.bin

error: symbol main not found
error: Try with -s to see all symbols.
error: If you have set the option --dump or --calls you need to set
error: the option -x (see --help).
```

I've tried with -s too, same error.

**Comment by joelpx** [comment]
I don't know why but I had already similar problems when installing a new python package.

-s is used to list all symbols in the binaries. With `reverse.py tests/nestedloop1.bin -s` you got nothing ?

What is the installed version of pyelftools (path/elftools/__init__.py) ? Mine is 0.23. Maybe you can try with the official repo : https://github.com/eliben/pyelftools/
