### ISSUE TITLE
GCC optimizations (-Os, -O2, -O3 but not -O1) cause KeyError

### ISSUE THREAD

**Issue by dnet** [joelpx/reverse#7]
The file `keyerror.c` has the following contents:

```c
int main(int argc, char **argv) {
    return 0;
}
```

I compiled several versions that only differ in optimization level:

    $ gcc     keyerror.c -o keyerror-normal
    $ gcc -O1 keyerror.c -o keyerror-o1
    $ gcc -O2 keyerror.c -o keyerror-o2
    $ gcc -O3 keyerror.c -o keyerror-o3
    $ gcc -Os keyerror.c -o keyerror-os

The first two work like it should:

    $ python3 reverse.py keyerror-normal
    function main {
        0x4004b6: push rbp
        0x4004b7: rbp = rsp # mov rbp, rsp
        0x4004ba: var1 = edi # mov dword ptr [rbp - 4], edi
        0x4004bd: var2 = rsi # mov qword ptr [rbp - 0x10], rsi
        0x4004c1: eax = 0 # mov eax, 0
        0x4004c6: pop rbp
        0x4004c7: ret
    }
    $ python3 reverse.py keyerror-o1
    function main {
        0x4004b6: eax = 0 # mov eax, 0
        0x4004bb: ret
    }

However, the other three cause `KeyError` like below:

    $ python3 reverse.py keyerror-o2
    Traceback (most recent call last):
      File "reverse.py", line 122, in <module>
        gph = dis.extract_func(addr)
      File "/home/dnet/_projekt/reverse/lib/disassembler.py", line 195, in extract_func
        curr = self.code[addr]
    KeyError: 4195264
    $ python3 reverse.py keyerror-o3
    Traceback (most recent call last):
      File "reverse.py", line 122, in <module>
        gph = dis.extract_func(addr)
      File "/home/dnet/_projekt/reverse/lib/disassembler.py", line 195, in extract_func
        curr = self.code[addr]
    KeyError: 4195264
    $ python3 reverse.py keyerror-os
    Traceback (most recent call last):
      File "reverse.py", line 122, in <module>
        gph = dis.extract_func(addr)
      File "/home/dnet/_projekt/reverse/lib/disassembler.py", line 195, in extract_func
        curr = self.code[addr]
    KeyError: 4195264

I zipped and uploaded the source file and the five binaries to http://vsza.hu/joelpx-reverse-issue-keyerror-20150318.zip

**Comment by dnet** [comment]
Just checked, `HEAD` doesn't have this issue. :+1:

**Comment by joelpx** [comment]
Yes i've juste checked.

**Comment by dnet** [comment]
I performed a bisect and it seems that you fixed it yesterday in a71db24a65b3a1d3e814f42e2a1353b1a8248b5a \o/
