### ISSUE TITLE
Bug with goto in a loop

### ISSUE THREAD

**Issue by joelpx** [joelpx/reverse#9]
#include <stdio.h>
    #include <stdlib.h>
    int main() {
        int i, j;
        if (i == 1) {
            printf("1\n");
            goto next;
        } else {
            printf("2\n");
        }
        while (i < 1) {
            printf("loop\n");
            if (j == 6) {
                printf("3\n");
            } else {
                printf("4\n");
            }
    next:
            if (j == 5) {
                printf("5\n");
            } else {
                printf("6\n");
            }
            i++;
        }
        return 0;
    }

When there is a "C-goto" which jump inside a loop, the program generate a wrong code.

**Comment by CoolOppo** [comment]
In case you didn't know, you can actually close an issue by referencing the issue number in the commit name.

https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by joelpx** [comment]
Thank you I didn't know that.
